// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatJSON(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadJSONFromFile(arg1:string):Promise<string>;

export function MinifyJSON(arg1:string):Promise<string>;

export function SaveJSONToFile(arg1:string,arg2:string):Promise<void>;

export function ValidateJSON(arg1:string):Promise<boolean>;
