// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatJSON(arg1) {
  return window['go']['main']['App']['FormatJSON'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadJSONFromFile(arg1) {
  return window['go']['main']['App']['LoadJSONFromFile'](arg1);
}

export function MinifyJSON(arg1) {
  return window['go']['main']['App']['MinifyJSON'](arg1);
}

export function SaveJSONToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveJSONToFile'](arg1, arg2);
}

export function ValidateJSON(arg1) {
  return window['go']['main']['App']['ValidateJSON'](arg1);
}
